name: Deploy Lambda (.NET 8)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.x"

    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    # Clean fresh publish output
    - name: Clean publish folder
      run: rm -rf src/HelloLambda/publish

    # Publish Lambda
    - name: Publish Lambda
      working-directory: src/HelloLambda
      run: |
        dotnet restore
        dotnet publish -c Release -o publish

    # Create ZIP *inside* publish folder
    - name: Create deployment zip
      working-directory: src/HelloLambda/publish
      run: |
        rm -f lambda.zip
        zip -r lambda.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # Upload new code to $LATEST
    - name: Upload Lambda package
      run: |
        aws lambda update-function-code \
          --function-name HelloLambda \
          --zip-file fileb://src/HelloLambda/publish/lambda.zip

    # Wait until Lambda finishes updating
    - name: Wait for Lambda
      run: aws lambda wait function-updated --function-name HelloLambda

    # Publish new version
    - name: Publish version
      id: pub
      run: |
        VERSION=$(aws lambda publish-version --function-name HelloLambda --query Version --output text)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # Update alias
    - name: Update alias prod
      run: |
        VERSION=${{ steps.pub.outputs.version }}
        if aws lambda get-alias --function-name HelloLambda --name prod >/dev/null 2>&1; then
          aws lambda update-alias --function-name HelloLambda --name prod --function-version $VERSION
        else
          aws lambda create-alias --function-name HelloLambda --name prod --function-version $VERSION
        fi
